/*
===========================================================================
ANALYSIS 5: MAGNITUDE ANALYSIS
===========================================================================
Formula: ∑ [Measures] By [Dimension]
Examples:
    - Total Sales By Country
    - Total Quantity By Category
    - Average Price By Product
    - Total Orders By Customer
===========================================================================
Purpose:
    - To add up important numbers and see how they are spread across different groups or categories.

Highlights:
    - Adds up values based on different categories or groups.
    - Helps us see the size and scale of data in simple terms.
    - Useful for spotting trends and patterns in totals.
===========================================================================
*/

--1. Find total customers by countries
SELECT
  country,
  COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

--2. Find total customers by gender
SELECT 
  gender,
  COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--3. Find total products by category
SELECT 
  category,
  COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--4. What is the average costs in each category?
SELECT 
  category,
  AVG(product_cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--5. What is the total revenue generated for each category?
SELECT 
  b.category,
  SUM(a.sales) AS total_revenue
FROM gold.fact_sales           AS a
LEFT JOIN gold.dim_products    AS b
ON a.product_key = b.product_key
GROUP BY b.category
ORDER BY total_revenue DESC

--6. Find total revenue is generated by each customer
SELECT 
  b.customer_id,
  b.first_name,
  b.last_name,
  SUM(a.sales) AS total_revenue
FROM gold.fact_sales             AS a
LEFT JOIN gold.dim_customers     AS b
  ON a.customer_id = b.customer_id
GROUP BY 
  b.customer_id,
  b.first_name,
  b.last_name
ORDER BY total_revenue DESC;

--7. What is the distribution of sold items across countries?

SELECT
  b.country ,
  SUM(a.quantity) AS total_sold_items
FROM gold.fact_sales                 AS a
LEFT JOIN gold.dim_customers         AS b
  ON a.customer_id = b.customer_id
GROUP BY
  b.country
ORDER BY 
  total_sold_items DESC



--NOTE: RUN them seperately. 
